# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 丁尉哲
  params:
    description: 丁尉哲的个人学术主页
    email: weizhedingphd@gmail.com
    phone: (+86) 188 4112 8665
  address:
    street: 崇山中路66号
    city: 沈阳
    region: 辽宁
    postcode: '110036'
    country: China
    country_code: CN
  coordinates:
    latitude: '41.840067'
    longitude: '123.41158'
  directions: 进入溯源楼并通过楼梯达到三楼304
  office_hours:
    - '周一-周五 10:00 ~ 18:00'
  menu:
    main:
      - name: 简介
        url: '#about'
        weight: 10
      - name: 经历
        url: '#experience'
        weight: 20
      - name: 著作
        url: '#publications'
        weight: 30
      - name: 项目
        url: '#projects'
        weight: 40
      - name: 荣誉
        url: '#accomplishments'
        weight: 50
      - name: 技能
        url: '#skills'
        weight: 60
      - name: 联系
        url: '#contact'
        weight: 70
      - name: 简历
        url: uploads/resume.pdf
        weight: 80
